device: cuda:1
out_dir: ./exp04
train:
  train_file: /home/ubuntu/ModelExtraction/data/Moments_in_time/rawframes/training/
  epochs: 500
  lr: 0.0003
  batch_size: 4
  num_workers: 4
  pin_memory: True
  shuffle: True
  #lambda 0 -> KL, lambda 1 -> CrossEnt
  lambda: 0.2
  #ratio of data for eval
  split_ratio: 0.1
  # eval frequency
  eval_freq: 5000
  # save frequency
  save_freq: 1

model:
  classes: 400
  #maxpool or weighted
  agg: weighted 
  backbone:
    #resnet or dla
    name: resnet                      

    #bottleneck or basic
    resnet_block: basic
    resnet_layers: [2, 2, 2, 2]

    #Version number for DLA in [34, 60, 102, 169]
    version: 60                       

    #Resnet version or 'imagenet' for dla
    pretrained: resnet18              

transform:
  input_size: 224  
